// Questions
var q = [
	'How do you divide responsibilities within your founding team? (SPC)',
	'Can you share an experience that showcases your team's unique strengths? (SPC)',
	'What processes do you have in place to maintain cohesion and trust within your team? (SPC)',
	'What inspired the foundation of your team and your startup? (SPC)',
	'How has your team's prior experience prepared you for this venture? (SPC)',
	'What is your startup's core mission, and how does it aim to impact society? (SPC)',
	'Can you describe a technical innovation your product brings to the market? (SPC)',
	'What limitations does your current product face, and how do you plan to address them? (SPC)',
	'How does your solution differentiate from existing competitors in the market? (SPC)',
	'What strategies do you have for user acquisition and growth? (SPC)',
	'What is your revenue model, and how have you planned your pricing strategy? (SPC)',
	'Can you detail your financial projections and key metrics for success? (SPC)',
	'How do you plan to engage and retain your users? (SPC)',
	'What milestones do you plan to achieve with your next round of funding? (SPC)',
	'What major challenges has your startup faced, and how have you overcome them? (SPC)',
	'How do you assess and mitigate potential risks to your business? (SPC)',
	'What legal or regulatory considerations are relevant to your product or service? (SPC)',
	'How does your startup generate and validate new ideas? (SPC)',
	'What plans do you have for scaling your solution and technology? (SPC)',
	'How do you plan to expand your product features or enter new markets? (SPC)',
	'In what ways does your startup contribute to educational equity and accessibility? (SPC)',
	'Can you share a personal motivation behind tackling the problem your startup addresses? (SPC)',
	'What long-term vision do you hold for your company and its societal impact? (SPC)',
	'How have you addressed feedback and adapted your product to user needs? (SPC)',
	'What are the critical hypotheses you wish to validate in the coming months? (SPC)',
	'Why is your team uniquely qualified to solve the problem you've identified? (SPC)',
	'How do you plan to measure the success of your user engagement strategies? (SPC)',
	'What has been your approach to previous funding rounds, and how have they impacted your progress? (SPC)',
	'Can you provide an example of a complex problem your team has successfully solved? (SPC)',
	'How does your startup plan to use funding to accelerate growth or product development? (SPC)',
	'How do you ensure your product remains innovative and ahead of market trends? (SPC)',
	'What steps have you taken to validate the market need for your product? (SPC)',
	'Can you explain a key piece of feedback from your users that led to a pivot or significant change? (SPC)',
	'How do you foresee your target market evolving, and how will you adapt? (SPC)',
	'What unique insights into your target audience have you gained that competitors might not see? (SPC)',
	'How do you assess the scalability of your technology infrastructure? (SPC)',
	'In what ways have you planned to diversify your revenue streams in the future? (SPC)',
	'Can you describe a failure your team encountered and what you learned from it? (SPC)',
	'How do you prioritize features or projects within your roadmap? (SPC)',
	'What strategies do you employ to stay compliant with data protection and privacy laws? (SPC)',
	'How does your product facilitate a better understanding or solution to global issues like climate change? (SPC)',
	'What partnerships or collaborations are you pursuing to enhance your product's value? (SPC)',
	'How do you balance rapid growth with maintaining a quality user experience? (SPC)',
	'What is your approach to intellectual property, and how do you protect your innovations? (SPC)',
	'How do you plan to maintain a competitive edge in a rapidly advancing technological landscape? (SPC)',
	'Can you share an example of how your product has already made a positive impact on a user or community? (SPC)',
	'How do you incorporate user feedback into your product development cycle? (SPC)',
	'What are the most significant barriers to adoption for your product, and how are you addressing them? (SPC)',
	'How do you manage and allocate resources for R&D within your startup? (SPC)',
	'What criteria do you use to decide when to expand into new markets or segments?',
	'What do you understand that others don&#39;t? (YC)',
	'Why will you succeed? (YC)',
	'How big an opportunity is there? (YC)',
	'What problems/hurdles are you anticipating? (YC)',
	'Who would use your product? (YC)',
	'How much does customer acquisition cost? (YC)',
	'How will you make money? (YC)',
	'How much money could you make per year? (YC)',
	'How many users do you have? (YC)',
	'What is your user growth rate? (YC)',
	'How many users are paying? (YC)',
	'How are you meeting customers? (YC)',
	'How are you understanding customer needs? (YC)',
	'How will you get users? (YC)',
	'Who would you hire or how would you add to your team? (YC)',
	'So what are you working on? (YC)',
	'Do you have a demo? (YC)',
	'Where is the rocket science here? (YC)',
	'How does your product work in more detail? (YC)',
	'How is your product different? (YC)',
	'What are you going to do next? (YC)',
	'What&#39;s new about what you make? (YC)',
	'What, exactly, makes you different from existing options? (YC)',
	'Who needs what you&#39;re making? (YC)',
	'How do you know customers need what you&#39;re making? (YC)',
	'Why isn&#39;t someone already doing this? (YC)',
	'What obstacles will you face and how will you overcome them? (YC)',
	'How will customers and/or users find out about you? (YC)',
	'What resistance will they have to trying you and how will you overcome it? (YC)',
	'What are the key things about your field that outsiders don&#39;t understand? (YC)',
	'What part of your project are you going to build first? (YC)',
	'Who is going to be your first paying customer? (YC)',
	'If your startup succeeds, what additional areas might you be able to expand into? (YC)',
	'Why did you choose this idea? (YC)',
	'What have you learned so far from working on your product? (YC)',
	'Six months from now, what&#39;s going to be your biggest problem? (YC)',
	'Where do new users come from? (YC)',
	'What is your growth like? (YC)',
	'What&#39;s the conversion rate? (YC)',
	'What makes new users try you? (YC)',
	'Why do the reluctant users hold back? (YC)',
	'What are the top things users want? (YC)',
	'What has surprised you about user behaviour? (YC)',
	'What&#39;s an impressive thing you have done? (YC)',
	'What do you understand about your users? (YC)',
	'Why did you pick this idea to work on? (YC)',
	'What domain expertise do you have? (YC)',
	'Who are your competitors? (YC)',
	'Who might become competitors? (YC)',
	'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have? (YC)',
	'What competition do you fear most? (YC)',
	'What is your distribution strategy? (YC)',
	'How did your team meet? (YC)',
	'Why did your team get together? (YC)',
	'Who in your team does what? (YC)',
	'Who is &quot;the boss&quot;? (YC)',
	'What will you do if we don&#39;t fund you? (YC)',
	'Would you relocate to Silicon Valley? (YC)',
	'How do we know your team will stick together? (YC)',
	'What else have you created together? (YC)',
	'Are you open to changing your idea?  (YC)',
	'What systems have you hacked? (YC)',
	'Tell us about a tough problem you solved? (YC)',
	'In what ways are you resourceful? (YC)',
	'Will you reincorporate as a US company? (YC)',
	'Will your team stick at this? (YC)',
	'Tell us something surprising you have done? (YC)',
	'What&#39;s the funniest thing that has happened to you? (YC)',
	'What&#39;s the worst thing that has happened? (YC)',
	'What&#39;s the biggest mistake you have made? (YC)',
	'What is your burn rate? (YC)',
	'How long can you go before funding? (YC)',
	'What is the next step with the product evolution? (YC)',
	'Have you raised funding? (YC)',
	'Who would be your next hire? (YC)',
	'How do you know people want this? (YC)',
	'What do you know about this space/product others don&#39;t know (YC)?'
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
