// Questions
var q = [
	'How do you come up with new ideas? Give a quick example.',
	'Tell us about an idea you stopped working on and why.',
	'What\'s the biggest market you\'ve thought about targeting? Why was it appealing?',
	'What\'s an interesting market you think is overlooked? Why?',
	'How do you see potential in the education market that others don\'t?',
	'What market does your current project address? Why did you choose it?',
	'How has your project changed over time? What drove those changes?',
	'Why isn\'t your project growing faster? What\'s holding it back?',
	'What new areas are you thinking of exploring with your project? How will you test these ideas?',
	'From your main goal, how do you pick which markets to go after?',
	'How do you figure out how much money your project could make in different markets?',
	'How do you use market data to estimate how well your project can do?',
	'What growth targets do you have for the next year? How will you hit them?',
	'Can you share a time when you saw an opportunity that others didn\'t? What happened?',
	'How do you decide between making something new and making sure it sells?',
	'Describe a big change you had to make based on what the market wanted.',
	'How have you solved problems creatively when things didn\'t go as planned?',
	'How do you use feedback to make your project better?',
	'What\'s your plan for competing in a busy market?',
	'Can you talk about a time you had to learn about a new market quickly? What did you do?',
	'How did each team member meet and how long have you known each other?',
	'What is your team\'s north star, and why is it significant?',
	'Can you list some ideas you\'re exploring to achieve your north star?',
	'What expertise does your team possess related to your north star?',
	'Describe the impact of your success on the world in 5-10 years.',
	'Could you share other ideas your team has considered?',
	'Can you link to a project you\'ve created, preferably as a team?',
	'What relevant experiences outside this project can you share?',
	'How does your team divide responsibilities?',
	'Highlight a unique experience that makes your team special.',
	'What problems are you eager to solve?',
	'What solutions have you already invalidated, and why?',
	'Describe your process for generating and validating new ideas.',
	'If funded, what are your immediate goals for the next few months?',
	'What hypotheses do you plan to validate with funding?',
	'How would funding change your current approach or capabilities?',
	'How do you prioritize tasks within the team?',
	'Share an example of overcoming a disagreement in your team.',
	'How does your team handle feedback and criticism?',
	'Describe a situation where you pivoted from an initial idea.',
	'What technology trends influence your project?',
	'How do you stay informed about developments in your field?',
	'Describe a challenge you anticipate and how you plan to address it.',
	'What inspired your team to work on this specific problem?',
	'How does your team celebrate successes or milestones?',
	'What motivates your team to work together on this project?',
	'How do you measure progress towards your north star?',
	'Share a learning moment from your project development.',
	'How do you ensure your project remains aligned with user needs?',
	'Describe how user feedback has shaped your project.',
	'What role does each team member play in decision-making?',
	'How do you balance project development with other commitments?',
	'In what ways has your vision evolved since starting the project?',
	'Describe how your team approaches risk management.',
	'How do you plan to scale your project for wider impact?',
	// 'What do you understand that others don&#39;t?',
	// 'Why will you succeed?',
	// 'How big an opportunity is there?',
	// 'What problems/hurdles are you anticipating?',
	// 'Who would use your product?',
	// 'How much does customer acquisition cost?',
	// 'How will you make money?',
	// 'How much money could you make per year?',
	// 'How many users do you have?',
	// 'What is your user growth rate?',
	// 'How many users are paying?',
	// 'How are you meeting customers?',
	// 'How are you understanding customer needs?',
	// 'How will you get users?',
	// 'Who would you hire or how would you add to your team?',
	
	// 'So what are you working on?',
	// 'Do you have a demo?',
	// 'Where is the rocket science here?',
	// 'How does your product work in more detail?',
	// 'How is your product different?',
	// 'What are you going to do next?',
	// 'What&#39;s new about what you make?',
	// 'What, exactly, makes you different from existing options?',
	// 'Who needs what you&#39;re making?',
	// 'How do you know customers need what you&#39;re making?',
	// 'Why isn&#39;t someone already doing this?',
	// 'What obstacles will you face and how will you overcome them?',
	// 'How will customers and/or users find out about you?',
	// 'What resistance will they have to trying you and how will you overcome it?',
	// 'What are the key things about your field that outsiders don&#39;t understand?',
	// 'What part of your project are you going to build first?',
	// 'Who is going to be your first paying customer?',
	// 'If your startup succeeds, what additional areas might you be able to expand into?',
	// 'Why did you choose this idea?',
	// 'What have you learned so far from working on your product?',
	// 'Six months from now, what&#39;s going to be your biggest problem?',
	// 'Where do new users come from?',
	// 'What is your growth like?',
	// 'What&#39;s the conversion rate?',
	// 'What makes new users try you?',
	// 'Why do the reluctant users hold back?',
	// 'What are the top things users want?',
	// 'What has surprised you about user behaviour?',
	// 'What&#39;s an impressive thing you have done?',
	// 'What do you understand about your users?',
	// 'Why did you pick this idea to work on?',
	// 'What domain expertise do you have?',
	// 'Who are your competitors?',
	// 'Who might become competitors?',
	// 'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	// 'What competition do you fear most?',
	// 'What is your distribution strategy?',
	// 'How did your team meet?',
	// 'Why did your team get together?',
	// 'Who in your team does what?',
	// 'Who is &quot;the boss&quot;?',
	// 'What will you do if we don&#39;t fund you?',
	// 'Would you relocate to Silicon Valley?',
	// 'How do we know your team will stick together?',
	// 'What else have you created together?',
	// 'Are you open to changing your idea? ',
	// 'What systems have you hacked?',
	// 'Tell us about a tough problem you solved?',
	// 'In what ways are you resourceful?',
	// 'Will you reincorporate as a US company?',
	// 'Will your team stick at this?',
	// 'Tell us something surprising you have done?',
	// 'What&#39;s the funniest thing that has happened to you?',
	// 'What&#39;s the worst thing that has happened?',
	// 'What&#39;s the biggest mistake you have made?',
	// 'What is your burn rate?',
	// 'How long can you go before funding?',
	// 'What is the next step with the product evolution?',
	// 'Have you raised funding?',
	// 'Who would be your next hire?',
	
	// 'How do you know people want this?',
	// 'What do you know about this space/product others don&#39;t know?'
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
