// Questions
var q = [
	'How do you approach generating new ideas, and can you give examples of this process in action?',
	'Describe an idea you initially believed in but decided to discard. What led to that decision?',
	'Of the ideas you\'ve pursued or considered, which had the largest potential market size, and why did you focus on this market?',
	'Can you identify a market you find fascinating but untapped? Why does it interest you?',
	'How have you evaluated the educational market\'s potential, and what opportunities do you see that others might not?',
	'Discuss a market you are currently exploring with your project. What attracted you to this market?',
	'Detail the evolution of your current project. What were the pivotal iterations, and why did they occur?',
	'Explain why your project hasn’t grown faster. What limitations or obstacles have you encountered?',
	'What new markets or directions are you considering for your project, and what experiments are you planning to validate these directions?',
	'Based on your project’s "north star," how do you identify and prioritize target markets and proxy markets?',
	'Describe how you would construct a market share and revenue flow model for your project.',
	'How do you perform top-down market analysis? Discuss how you use growth rates and market data to forecast potential revenues.',
	'What are the key growth numbers and targets you aim to achieve in the next year, and how do you plan to reach them?',
	'Can you share an instance where your understanding of a market or a product was counterintuitive to the general consensus but proved correct?',
	'How do you balance the need for product innovation with the necessity of reaching market-driven revenue targets?',
	'Discuss a time when you had to pivot significantly in your approach or product based on market feedback or analysis.',
	'In what ways have you demonstrated resourcefulness in navigating market uncertainties or in product development?',
	'How do you measure and evaluate customer or user feedback to inform product iterations and market strategy?',
	'What strategies do you employ for entering and competing in markets with established players?',
	'Describe a tough challenge you faced in understanding a new market, and how did you overcome it?',
	// 'What do you understand that others don&#39;t?',
	// 'Why will you succeed?',
	// 'How big an opportunity is there?',
	// 'What problems/hurdles are you anticipating?',
	// 'Who would use your product?',
	// 'How much does customer acquisition cost?',
	// 'How will you make money?',
	// 'How much money could you make per year?',
	// 'How many users do you have?',
	// 'What is your user growth rate?',
	// 'How many users are paying?',
	// 'How are you meeting customers?',
	// 'How are you understanding customer needs?',
	// 'How will you get users?',
	// 'Who would you hire or how would you add to your team?',
	
	// 'So what are you working on?',
	// 'Do you have a demo?',
	// 'Where is the rocket science here?',
	// 'How does your product work in more detail?',
	// 'How is your product different?',
	// 'What are you going to do next?',
	// 'What&#39;s new about what you make?',
	// 'What, exactly, makes you different from existing options?',
	// 'Who needs what you&#39;re making?',
	// 'How do you know customers need what you&#39;re making?',
	// 'Why isn&#39;t someone already doing this?',
	// 'What obstacles will you face and how will you overcome them?',
	// 'How will customers and/or users find out about you?',
	// 'What resistance will they have to trying you and how will you overcome it?',
	// 'What are the key things about your field that outsiders don&#39;t understand?',
	// 'What part of your project are you going to build first?',
	// 'Who is going to be your first paying customer?',
	// 'If your startup succeeds, what additional areas might you be able to expand into?',
	// 'Why did you choose this idea?',
	// 'What have you learned so far from working on your product?',
	// 'Six months from now, what&#39;s going to be your biggest problem?',
	// 'Where do new users come from?',
	// 'What is your growth like?',
	// 'What&#39;s the conversion rate?',
	// 'What makes new users try you?',
	// 'Why do the reluctant users hold back?',
	// 'What are the top things users want?',
	// 'What has surprised you about user behaviour?',
	// 'What&#39;s an impressive thing you have done?',
	// 'What do you understand about your users?',
	// 'Why did you pick this idea to work on?',
	// 'What domain expertise do you have?',
	// 'Who are your competitors?',
	// 'Who might become competitors?',
	// 'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	// 'What competition do you fear most?',
	// 'What is your distribution strategy?',
	// 'How did your team meet?',
	// 'Why did your team get together?',
	// 'Who in your team does what?',
	// 'Who is &quot;the boss&quot;?',
	// 'What will you do if we don&#39;t fund you?',
	// 'Would you relocate to Silicon Valley?',
	// 'How do we know your team will stick together?',
	// 'What else have you created together?',
	// 'Are you open to changing your idea? ',
	// 'What systems have you hacked?',
	// 'Tell us about a tough problem you solved?',
	// 'In what ways are you resourceful?',
	// 'Will you reincorporate as a US company?',
	// 'Will your team stick at this?',
	// 'Tell us something surprising you have done?',
	// 'What&#39;s the funniest thing that has happened to you?',
	// 'What&#39;s the worst thing that has happened?',
	// 'What&#39;s the biggest mistake you have made?',
	// 'What is your burn rate?',
	// 'How long can you go before funding?',
	// 'What is the next step with the product evolution?',
	// 'Have you raised funding?',
	// 'Who would be your next hire?',
	
	// 'How do you know people want this?',
	// 'What do you know about this space/product others don&#39;t know?'
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];
